import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { projects, services } from '@/data/content';
import HeroVisualCarousel from '@/components/HeroVisualCarousel';
export const metadata: Metadata={title:'Services | Product Research, Strategy, Marketing & Development',description:'Explore ABE TechLab services across product research, strategy, marketing, design, development and delivery, with selected work delivered for real organisations.',alternates:{canonical:'/services'}};
const heroVisuals=[{src:'https://images.pexels.com/photos/7988758/pexels-photo-7988758.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Technology team presenting and discussing a project'},{src:'https://images.pexels.com/photos/12899191/pexels-photo-12899191.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Developers discussing software development in an office'},{src:'https://images.pexels.com/photos/7988742/pexels-photo-7988742.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Developers collaborating on technology work'}];
export default function Services(){return <div>
<section className="relative overflow-hidden grid-bg"><HeroVisualCarousel visuals={heroVisuals}/><div className="container relative z-10 py-20 md:py-32"><p className="text-xs font-semibold uppercase tracking-[.18em] text-black/45">Services</p><h1 className="font-display mt-5 max-w-5xl text-5xl font-semibold leading-[.9] tracking-[-.07em] sm:text-6xl md:mt-6 md:text-8xl">Product thinking, design and technology in one place.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-black/55 md:mt-8 md:text-lg">We help organisations move from ideas and operational problems to clearer products, stronger systems and technology that works in practice.</p></div></section>
<section className="container py-16 md:py-28"><div className="mb-10 max-w-2xl"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-black/40">What we do</p><h2 className="font-display mt-4 text-4xl font-semibold tracking-[-.05em] md:text-6xl">Services across the product lifecycle.</h2></div>
<div className="hidden divide-y divide-black/15 border-t border-black/15 md:block">{services.map(s=><article key={s.number} className="grid gap-8 py-12 md:grid-cols-[80px_1fr_1fr] md:py-16"><span className="text-xs text-black/35">{s.number}</span><div><h3 className="font-display text-3xl font-semibold tracking-[-.045em] md:text-4xl">{s.title}</h3><p className="mt-4 max-w-md text-sm leading-7 text-black/55">{s.text}</p></div><ul className="grid content-start gap-3 text-sm text-black/65">{s.items.map(item=><li key={item} className="flex items-center gap-3"><span className="h-1 w-1 bg-black"/>{item}</li>)}</ul></article>)}</div>
<div className="grid gap-2 md:hidden">{services.map(s=><article key={s.number} className="border border-black/10 bg-white/65 p-5"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold tracking-[.18em] text-black/30">{s.number}</span><span className="text-[10px] uppercase tracking-[.14em] text-black/35">Service</span></div><h3 className="font-display mt-5 text-2xl font-semibold tracking-[-.04em]">{s.title}</h3><p className="mt-2 text-sm leading-6 text-black/55">{s.text}</p><div className="mt-5 flex flex-wrap gap-2">{s.items.slice(0,3).map(item=><span key={item} className="border border-black/10 px-2.5 py-1.5 text-[10px] text-black/50">{item}</span>)}</div><Link href="/contact" className="mt-5 inline-flex items-center gap-2 text-xs font-semibold">Talk about this <ArrowUpRight size={15}/></Link></article>)}</div>
</section>
<section id="selected-work" className="scroll-mt-24 bg-[#11110f] py-20 text-white md:py-28"><div className="container"><div className="mb-10 max-w-3xl md:mb-12"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-white/45">Selected work</p><h2 className="font-display mt-4 text-4xl font-semibold tracking-[-.05em] md:text-6xl">What this work looks like in practice.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/60">A few examples of where we have applied these capabilities, working as product strategists, managers, developers and technology partners.</p></div><div className="grid gap-2 md:grid-cols-2">{projects.map((p,index)=><article key={p.name} className={`${index === projects.length - 1 ? 'md:col-span-2' : ''} border border-white/10 bg-[#11110f] p-6 md:border-0 md:bg-[#11110f] md:p-10`}><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/40">{p.category}</p><h3 className="font-display mt-4 text-2xl font-semibold tracking-[-.045em] md:mt-5 md:text-3xl">{p.name}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-white/60">{p.description}</p></article>)}</div></div></section>
<section className="container py-20 md:py-32"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr]"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-black/40">Start with the problem</p><div><h2 className="font-display text-4xl font-semibold tracking-[-.05em] md:text-6xl">Not sure which service you need? That's part of the conversation.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-black/55">We can help define the problem, shape the product direction and decide what should be built before moving into design, development or delivery.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 bg-black px-6 py-4 text-sm font-semibold text-white transition hover:-translate-y-1">Talk about your product <ArrowUpRight size={17}/></Link></div></div></section></div>}
