"use client";
import { FormEvent, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import HeroVisualCarousel from '@/components/HeroVisualCarousel';
import MobileContactForm from '@/components/MobileContactForm';

const needs=['New product idea','Website or web application','Product research / strategy','Product marketing / positioning','Product design','Development','Product management','Education / teaching technology','Existing product improvement','Something else'];
const followUpChannels=[
  {value:'website_chat',label:'Chat with our assistant here',description:'Open the assistant on this website after you submit.'},
  {value:'whatsapp',label:'Continue on WhatsApp',description:'Open WhatsApp with your enquiry ready to continue.'},
  {value:'voice_call',label:'Call our AI assistant',description:'Get a call button after you submit and speak directly with the assistant.'},
  {value:'email',label:'Continue by email',description:'The assistant will email you and continue when you reply.'},
];
const heroVisuals=[{src:'https://images.pexels.com/photos/574077/pexels-photo-574077.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Developer working with code on a laptop'},{src:'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Developer working with a laptop and smartphone'},{src:'https://images.pexels.com/photos/7988758/pexels-photo-7988758.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Technology team discussing a project'}];

type ChannelLinks={whatsapp:string|null;call:string|null};
const EMPTY_LINKS:ChannelLinks={whatsapp:null,call:null};

export default function Contact(){
 const [sending,setSending]=useState(false); const [status,setStatus]=useState<'idle'|'success'|'error'>('idle'); const [leadId,setLeadId]=useState<string|null>(null); const [selectedChannel,setSelectedChannel]=useState(''); const [assistantStarted,setAssistantStarted]=useState(false); const [channelLinks,setChannelLinks]=useState<ChannelLinks>(EMPTY_LINKS); const [channelLinksLoading,setChannelLinksLoading]=useState(false);
 async function loadChannelLinks(id:string){setChannelLinksLoading(true);try{const response=await fetch(`/api/assistant/channel-links?lead_id=${encodeURIComponent(id)}`,{cache:'no-store'});if(!response.ok){setChannelLinks(EMPTY_LINKS);return;}const result=await response.json();setChannelLinks({whatsapp:result.whatsapp??null,call:result.call??null});}catch{setChannelLinks(EMPTY_LINKS)}finally{setChannelLinksLoading(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(sending)return;setSending(true);setStatus('idle');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());const channel=String(data.preferred_channel||'');setSelectedChannel(channel);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');const id=String(result.lead_id||'');if(id){setLeadId(id);window.localStorage.setItem('abe_assistant_lead_id',id);window.dispatchEvent(new Event('abe-assistant-context'));}setAssistantStarted(Boolean(result.assistant?.started));if(channel==='website_chat')window.dispatchEvent(new Event('abe-assistant-open'));if(id&&(channel==='whatsapp'||channel==='voice_call'))await loadChannelLinks(id);else setChannelLinks(EMPTY_LINKS);form.reset();setStatus('success')}catch{setStatus('error')}finally{setSending(false)}}
 return <div>
  <section className="relative overflow-hidden grid-bg"><HeroVisualCarousel visuals={heroVisuals}/><div className="container relative z-10 py-20 md:py-32"><p className="text-xs font-semibold uppercase tracking-[.18em] text-black/45">Contact</p><h1 className="font-display mt-5 max-w-5xl text-5xl font-semibold leading-[.9] tracking-[-.07em] sm:text-6xl md:mt-6 md:text-8xl">Let's talk about what you're building.</h1><p className="mt-6 max-w-xl text-base leading-7 text-black/55 md:mt-8 md:text-lg">Have a product idea, an education technology concept, an existing platform, a research question or a problem you're trying to solve? You don't need a perfect brief to start.</p></div></section>
  <section className="container py-16 md:py-28"><div className="mobile-only-scan"><div className="rounded-[2px] border border-black/10 bg-white/50 p-5 shadow-[0_18px_50px_rgba(17,17,15,.05)]"><MobileContactForm /></div></div>
   <div className="desktop-only-scan grid gap-16 md:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm leading-7 text-black/55">Tell us what you know. A problem, an idea or a rough direction is enough to begin the conversation. We'll use the details to understand where we can help.</p><div className="mt-10 border-t border-black/10 pt-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-black/40">Typical starting points</p><div className="mt-4 flex flex-wrap gap-2">{['Research','Strategy','Product marketing','Design','Development','Education technology'].map(x=><span key={x} className="border border-black/10 px-3 py-2 text-xs text-black/55">{x}</span>)}</div></div></div>
    <form onSubmit={submit} className="space-y-8" aria-busy={sending}>
     {([['name','Name','text'],['email','Email','email'],['phone','Phone number','tel'],['company','Company / Organization','text']] as const).map(([id,label,type])=><label key={id} className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-black/45">{label}</span><input required={id==='name'||id==='email'} id={id} name={id} type={type} autoComplete={id==='phone'?'tel':id==='email'?'email':id==='name'?'name':'organization'} className="w-full border-b border-black/20 bg-transparent px-0 py-3 outline-none transition focus:border-black focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#b7ff3c]"/></label>)}
     <fieldset><legend className="mb-4 text-xs font-semibold uppercase tracking-[.14em] text-black/45">What do you need help with?</legend><div className="grid gap-2 sm:grid-cols-2">{needs.map(need=><label key={need} className="flex cursor-pointer items-center gap-3 border border-black/10 bg-white/40 px-4 py-3 text-sm text-black/60 transition hover:border-black/25 hover:bg-white focus-within:border-[#b7ff3c]"><input type="radio" name="need" value={need} required className="accent-black"/>{need}</label>)}</div></fieldset>
     <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-black/45">Expected timeline</span><select name="timeline" required className="w-full border-b border-black/20 bg-transparent px-0 py-3 outline-none transition focus:border-black focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[#b7ff3c]"><option value="">Select if you know</option><option>As soon as possible</option><option>Within 1–3 months</option><option>Within 3–6 months</option><option>Exploring / no fixed timeline</option></select></label>
     <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-black/45">Tell us about the project</span><textarea required name="message" rows={6} placeholder="What are you trying to build, research or improve?" className="w-full resize-none border-b border-black/20 bg-transparent px-0 py-3 outline-none transition placeholder:text-black/25 focus:border-black focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#b7ff3c]"/></label>
     <fieldset><legend className="mb-4 text-xs font-semibold uppercase tracking-[.14em] text-black/45">How would you like to continue?</legend><p className="mb-4 text-sm leading-6 text-black/50">Choose where you'd like our assistant to continue the conversation after you submit.</p><div className="grid gap-2 sm:grid-cols-2">{followUpChannels.map(channel=><label key={channel.value} className="flex cursor-pointer items-start gap-3 border border-black/10 bg-white/40 px-4 py-4 text-sm text-black/65 transition hover:border-black/25 hover:bg-white focus-within:border-[#b7ff3c]"><input type="radio" name="preferred_channel" value={channel.value} required className="mt-1 accent-black"/><span><span className="block font-medium text-black/75">{channel.label}</span><span className="mt-1 block text-xs leading-5 text-black/45">{channel.description}</span></span></label>)}</div></fieldset>
     <button type="submit" disabled={sending} aria-disabled={sending} className="btn-primary inline-flex items-center gap-2 px-6 py-4 text-sm font-semibold transition disabled:cursor-wait disabled:opacity-60 focus-visible:outline-3 focus-visible:outline-offset-3 focus-visible:outline-[#b7ff3c]">{sending?'Sending…':'Send enquiry'} <ArrowUpRight size={16}/></button>
     <div aria-live="polite" aria-atomic="true">
       {status==='success'&&<div className="space-y-3"><p className="text-sm leading-6 text-black/55">Thanks. Your enquiry is in. {assistantStarted?'The assistant has started the selected follow-up.':'Your selected continuation route is ready.'}</p>{selectedChannel==='whatsapp'&&(channelLinksLoading?<p className="text-xs text-black/45">Preparing WhatsApp…</p>:channelLinks.whatsapp?<a href={channelLinks.whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-black/15 px-4 py-3 text-sm font-semibold">Continue on WhatsApp <ArrowUpRight size={15}/></a>:<p className="text-xs text-black/45">WhatsApp is not configured on the assistant yet.</p>)}{selectedChannel==='voice_call'&&(channelLinksLoading?<p className="text-xs text-black/45">Preparing the AI call…</p>:channelLinks.call?<a href={channelLinks.call} className="inline-flex items-center gap-2 border border-black/15 px-4 py-3 text-sm font-semibold">Call the AI assistant <ArrowUpRight size={15}/></a>:<p className="text-xs text-black/45">The AI phone number is not configured yet.</p>)}{selectedChannel==='website_chat'&&<p className="text-xs text-black/45">The Assistant chat has been opened for you.</p>}{selectedChannel==='email'&&<p className="text-xs text-black/45">Check your inbox. The Assistant will continue when you reply.</p>}</div>}
       {status==='error'&&<p className="text-sm leading-6 text-black/55" role="alert">We couldn't send the enquiry right now. Please try again shortly.</p>}
     </div>
    </form>
   </div>
  </section></div>
}
