import type { Metadata } from 'next';
import { ArrowUpRight, Cpu, UserRound } from 'lucide-react';
import { team } from '@/data/team';
import HeroVisualCarousel from '@/components/HeroVisualCarousel';

export const metadata: Metadata = { title: 'Team | ABE TechLab', description: 'Meet the people and AI systems behind ABE TechLab.', alternates: { canonical: '/team' } };
const heroVisuals=[
 {src:'https://images.pexels.com/photos/7988742/pexels-photo-7988742.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Technology team collaborating around a computer'},
 {src:'https://images.pexels.com/photos/12899167/pexels-photo-12899167.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Software developers working together'},
 {src:'https://images.pexels.com/photos/19805878/pexels-photo-19805878.jpeg?auto=compress&cs=tinysrgb&w=1800',alt:'Developer focused on technology work in an office'}
];
export default function TeamPage(){return <main>
<section className="relative isolate overflow-hidden border-b border-black/10 bg-[#ecece6]"><HeroVisualCarousel visuals={heroVisuals}/><div className="container relative z-10 py-24 md:py-32"><p className="mb-6 text-[10px] font-semibold uppercase tracking-[.22em] text-black/55">The team</p><h1 className="font-display max-w-4xl text-6xl font-semibold leading-[.88] tracking-[-.07em] text-[#0b0b0a] md:text-8xl">Human thinking.<br/>AI-augmented.</h1><p className="mt-8 max-w-2xl text-base font-medium leading-8 text-black/70 md:text-lg">ABE TechLab is built to grow as a studio. Our team combines human product leadership with AI-assisted research and technology, with more specialists joining as the work grows.</p></div></section>
<section className="container py-24 md:py-32"><div className="grid gap-5 md:grid-cols-2">{team.map(member=><article key={member.name} className="group border border-black/10 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:border-black/25 hover:shadow-[0_18px_45px_rgba(0,0,0,.07)] md:p-9"><div className="flex items-start justify-between gap-5"><div className={`flex h-24 w-24 items-center justify-center border ${member.type==='AI'?'border-[#b7ff3c] bg-[#11110f] text-[#b7ff3c]':'border-black/10 bg-[#ecece6] text-black'} font-display text-xl font-semibold`}>{member.type==='AI'?<Cpu size={30} strokeWidth={1.5}/>:<UserRound size={30} strokeWidth={1.5}/>}</div><span className={`inline-flex items-center gap-2 border px-3 py-2 text-[9px] font-semibold uppercase tracking-[.18em] ${member.type==='AI'?'border-[#b7ff3c]/60 bg-[#b7ff3c]/15 text-black':'border-black/10 text-black/45'}`}><span className={`h-1.5 w-1.5 rounded-full ${member.type==='AI'?'bg-[#8ccf00]':'bg-black/30'}`}/>{member.type}</span></div><h2 className="font-display mt-16 text-3xl font-semibold tracking-[-.045em]">{member.name}</h2><p className="mt-2 text-sm font-medium text-black/55">{member.role}</p><p className="mt-6 max-w-lg text-sm leading-7 text-black/55">{member.bio}</p>{member.note&&<p className="mt-6 border-t border-black/10 pt-4 text-[10px] font-semibold uppercase tracking-[.14em] text-black/35">{member.note}</p>}</article>)}</div></section>
<section className="border-y border-black/10 bg-[#11110f] py-24 text-white md:py-28"><div className="container flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><p className="mb-5 text-[10px] font-semibold uppercase tracking-[.22em] text-white/35">Growing the studio</p><h2 className="font-display max-w-2xl text-4xl font-semibold leading-[.92] tracking-[-.055em] md:text-6xl">The team grows with the work.</h2></div><a href="/contact" className="inline-flex w-fit items-center gap-2 border border-white/20 px-5 py-3 text-sm font-semibold text-white transition hover:border-white/50">Work with ABE TechLab <ArrowUpRight size={16}/></a></div></section>
</main>}
