import Link from 'next/link';
import { ArrowUpRight, Plus } from 'lucide-react';
import { projects, services } from '@/data/content';

function SectionLabel({children}:{children:React.ReactNode}){return <p className="mb-5 text-xs font-semibold uppercase tracking-[.18em] text-black/45">{children}</p>}
function ProjectCard({p,i}:{p:(typeof projects)[number];i:number}){return <Link href="/work" className="group block border-t border-black/15 py-7"><div className="grid gap-5 md:grid-cols-[90px_1fr_auto] md:items-start"><span className="text-xs text-black/35">0{i+1}</span><div><p className="mb-2 text-xs uppercase tracking-[.14em] text-black/45">{p.category}</p><h3 className="font-display text-2xl font-semibold tracking-[-.04em] md:text-3xl">{p.name}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-black/55">{p.description}</p></div><ArrowUpRight className="transition group-hover:translate-x-1 group-hover:-translate-y-1"/></div></Link>}
export default function Home(){return <>
<section className="grid-bg"><div className="container flex min-h-[calc(100vh-72px)] flex-col justify-center py-24"><div className="reveal max-w-5xl"><p className="mb-8 text-xs font-semibold uppercase tracking-[.2em] text-black/50">PRODUCT · DESIGN · TECHNOLOGY</p><h1 className="font-display text-[clamp(3.5rem,8vw,7.7rem)] font-semibold leading-[.88] tracking-[-.075em]">We design, build and move digital products forward.</h1><div className="mt-10 flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><p className="max-w-xl text-base leading-7 text-black/60 md:text-lg">ABE TechLab is a product and technology studio helping founders and businesses turn ideas into useful digital products, from strategy and design to development and launch.</p><div className="flex shrink-0 gap-3"><Link href="/contact" className="bg-black px-6 py-4 text-sm font-semibold text-white transition hover:-translate-y-1">Start a project</Link><Link href="/work" className="border border-black/20 px-6 py-4 text-sm font-semibold transition hover:border-black">View our work</Link></div></div></div><div className="mt-24 flex items-center gap-3 text-xs uppercase tracking-[.16em] text-black/35"><span className="h-px w-10 bg-black/20"/> Independent product studio</div></div></section>
<section className="container py-28"><SectionLabel>What we do</SectionLabel><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><h2 className="font-display max-w-md text-4xl font-semibold leading-tight tracking-[-.05em] md:text-5xl">From idea to shipped product.</h2><div className="divide-y divide-black/15">{services.map(s=><div key={s.number} className="py-7 first:pt-0"><div className="flex gap-6"><span className="text-xs text-black/35">{s.number}</span><div><h3 className="font-display text-2xl font-semibold tracking-[-.035em]">{s.title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-black/55">{s.text}</p></div></div></div>)}</div></div></section>
<section className="bg-black text-white"><div className="container py-28"><SectionLabel>Selected work</SectionLabel><div className="grid gap-12 md:grid-cols-[.75fr_1.25fr]"><div><h2 className="font-display text-4xl font-semibold tracking-[-.05em] md:text-5xl">Products, platforms and systems we've helped shape.</h2><Link href="/work" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-white/70 transition hover:text-white">View all work <ArrowUpRight size={16}/></Link></div><div className="border-t border-white/20">{projects.slice(0,4).map((p,i)=><div key={p.name} className="border-b border-white/20"><ProjectCard p={p} i={i}/></div>)}</div></div></div></section>
<section className="container py-28"><SectionLabel>How we work</SectionLabel><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><h2 className="font-display text-4xl font-semibold tracking-[-.05em] md:text-5xl">Good products don't happen by accident.</h2><p className="mt-6 max-w-md text-sm leading-7 text-black/55">We give ideas structure, then move them toward something people can actually use.</p></div><div className="divide-y divide-black/15 border-t border-black/15">{[['01','Discover','Understand the problem, users and opportunity.'],['02','Define','Turn requirements and ideas into a clear product direction.'],['03','Design','Shape the experience, interface and product structure.'],['04','Build','Develop, test and refine the product.'],['05','Launch','Ship, learn and improve.']].map(([n,t,d])=><div key={n} className="grid grid-cols-[48px_1fr] gap-5 py-6"><span className="text-xs text-black/35">{n}</span><div><h3 className="font-display text-xl font-semibold">{t}</h3><p className="mt-1 text-sm text-black/55">{d}</p></div></div>)}</div></div></section>
<section className="border-t border-black/10"><div className="container py-28"><div className="max-w-4xl"><SectionLabel>About ABE TechLab</SectionLabel><h2 className="font-display text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-7xl">Small studio. Serious products.</h2><p className="mt-8 max-w-2xl text-base leading-7 text-black/60">ABE TechLab works at the intersection of product, design and technology. We help turn early ideas into structured products and help existing products become clearer, more useful and easier to grow.</p><p className="mt-5 max-w-2xl text-base leading-7 text-black/60">We don't believe every project needs a large agency. It needs the right thinking, the right people and a clear path to shipping.</p></div></div></section>
<section className="bg-[#b7ff3c]"><div className="container flex flex-col gap-8 py-24 md:flex-row md:items-end md:justify-between"><div><SectionLabel>Start a conversation</SectionLabel><h2 className="font-display max-w-2xl text-5xl font-semibold leading-[.95] tracking-[-.06em] md:text-7xl">Have something worth building?</h2><p className="mt-6 max-w-xl text-black/65">Tell us what you're working on. We'll help you figure out what comes next.</p></div><Link href="/contact" className="flex shrink-0 items-center gap-3 bg-black px-6 py-4 text-sm font-semibold text-white transition hover:-translate-y-1">Start a project <ArrowUpRight size={17}/></Link></div></section>
</>}
