export type InsightCategory = 'Research' | 'Product' | 'Technology' | 'Perspectives';
export type Insight = { slug:string; title:string; excerpt:string; category:InsightCategory; publishedAt:string; readTime:string; content:string[] };

export const insights: Insight[] = [
  {slug:'what-abe-techlab-builds',title:'What ABE TechLab Actually Builds',excerpt:'A look at the product, research, technology and education work behind ABE TechLab.',category:'Product',publishedAt:'2026-08-16',readTime:'5 min read',content:[
    'ABE TechLab sits at the point where an idea becomes a usable product. That work can start with a research question, a business problem, a product that needs direction, or a rough concept that has not yet been tested. The important part is that we do not treat the first requested feature as the whole problem.',
    'Our work spans product research, product strategy, product marketing, product design and development. These are connected activities. Research helps reduce uncertainty. Strategy turns evidence into decisions. Design makes those decisions understandable and usable. Development turns them into working software. Product marketing helps the finished product reach the people it was designed for.',
    'That also means our work is not limited to one type of technology. We work on web products, systems, education technology, teaching technology and other digital experiences where there is a real problem to solve. Projects such as TechTrack and the systems we shape around organisations illustrate different parts of that product-building approach without changing the underlying principle: understand the problem, then build deliberately.',
    'We also think about the people around a product, not only the person clicking the interface. A school platform may need to work for students, teachers, administrators and decision makers. A marketplace needs to account for buyers, sellers, trust and the information that helps both sides act. A digital service needs to fit the actual workflow around it.',
    'In practice, that means a project can begin with discovery and end with a deployed product, or it can enter somewhere in the middle. Sometimes the right answer is to build. Sometimes it is to validate an assumption first. Sometimes it is to simplify an existing product before adding more features.',
    'The common thread is useful technology. We are interested in products that make a process clearer, reduce avoidable friction, create better access to information, or help people do something that was previously harder to do. That is the kind of work we want this journal to document.'
  ]},
  {slug:'why-product-research-comes-before-building',title:'Why Product Research Should Come Before Building',excerpt:'Good product development starts by understanding the problem, people and opportunity before deciding what to build.',category:'Research',publishedAt:'2026-08-16',readTime:'6 min read',content:[
    'One of the easiest mistakes in product development is starting with a feature list before understanding the problem. A polished interface can still be a poor product if it solves the wrong problem, serves the wrong audience or asks people to change a workflow they do not actually want to change.',
    'Research creates a pause between an idea and an expensive build. The goal is not to produce a giant report. The goal is to reduce important uncertainty early enough that the team can still change direction.',
    'A useful research cycle starts by identifying assumptions. Who has the problem? How do they handle it today? What is frustrating about the current approach? Which parts are genuinely important, and which parts only sound important because they were suggested in the original idea? Those questions give a team something concrete to investigate.',
    'Interviews are useful because they reveal language, habits and workarounds. Observation can reveal steps people forget to mention because the steps are routine. Market and competitor research can show how similar problems are already being addressed. Small experiments can test whether a proposed solution is understandable before a full product is built.',
    'Research also helps product teams distinguish a user request from a user need. Someone may ask for a dashboard, for example, when the underlying problem is that they cannot quickly tell what needs attention. The dashboard may be one solution, but the real product question is how to make the important signal visible and actionable.',
    'The best time to discover a wrong assumption is before it has become a large codebase, a complicated launch plan or a significant marketing promise. That is why research should not be treated as paperwork before the real work starts. It is part of the real work.',
    'There is also a practical limit. Research should not become endless discovery that delays action. Once the highest-risk assumptions have enough evidence behind them, the team should turn the learning into decisions, define an initial product scope and build something that can generate the next round of learning.',
    'Good research therefore does not replace building. It makes building more intentional.'
  ]},
  {slug:'teaching-technology-is-more-than-an-lms',title:'Teaching Technology Is More Than an LMS',excerpt:'Technology for education should support the people doing the teaching, not only the platform where lessons are stored.',category:'Perspectives',publishedAt:'2026-08-16',readTime:'6 min read',content:[
    'An LMS, or Learning Management System, can organise courses, lessons, assessments and records. That is useful, but teaching technology has a wider job: helping the people inside the learning system teach, learn, monitor progress and respond to problems.',
    'A student may interact with the course interface, but a teacher may be working across lesson planning, attendance, assessment, feedback, communication and progress monitoring at the same time. A school administrator may care about enrolment, reporting, payments, staff workflows and parent communication. A useful education product has to account for those connected realities.',
    'This changes how we think about product design. The question is not only whether a student can complete a lesson. It is also whether the teacher can understand what happened next. Can they see where learners are struggling? Can they adapt the pace? Can they communicate feedback without creating another disconnected process?',
    'The same applies to institutions. A platform that is pleasant for students but difficult for administrators can create operational work that erases the benefits. Likewise, a system that collects a lot of information without making that information useful can add reporting without improving decisions.',
    'Teaching technology should therefore be designed around workflows, not just screens. Sometimes the best feature is a simple view that turns scattered information into one understandable decision. Sometimes it is an offline-friendly workflow, a clearer communication channel or a smaller number of steps for a routine task.',
    'TechTrack is one part of ABE TechLab’s exploration of this space. The broader lesson is that education products need to respect the full learning system: students, teachers, institutions and the people supporting them.',
    'When technology is designed around that whole system, the product can become more than a place to store lessons. It can become infrastructure that helps teaching work better.'
  ]},
  {slug:'from-construction-problem-to-procurement-platform',title:'From a Construction Problem to a Procurement Platform',excerpt:'How product thinking can turn a fragmented construction procurement experience into a clearer digital marketplace.',category:'Technology',publishedAt:'2026-08-16',readTime:'6 min read',content:[
    'Construction procurement involves more than finding a product. People need to know what is available, who supplies it, what it costs, whether the specification is right, how to make contact and what happens after the first conversation. When those pieces are fragmented, the search itself becomes part of the problem.',
    'BuMarS is a construction ecosystem, and PROQUREMENT is the builders marketplace being developed within it. The product direction starts with a simple idea: make discovery of building materials and relevant suppliers easier and more structured.',
    'That sounds like a marketplace problem, but the product challenge is broader. A catalogue alone does not create trust. Users need useful categorisation, understandable information and a straightforward path from discovery to action. Suppliers also need a way to present what they actually offer without being buried inside an undifferentiated directory.',
    'This is where product thinking becomes important. Instead of beginning with every possible marketplace feature, the team can ask what the smallest useful transaction looks like. What information does a buyer need before making contact? What information does a seller need to provide? Which parts can be simplified or handled outside the platform in an early phase?',
    'A construction product also has to respect the context in which people already work. Phone calls, messaging, relationships and local knowledge may remain important even when software improves discovery. The goal is not to replace every existing behaviour. The goal is to remove unnecessary friction around it.',
    'That makes a procurement platform an interesting product problem: the value comes from better coordination as much as better screens. Discovery, trust, categorisation and action have to connect.',
    'The lesson extends beyond construction. Whenever a market is fragmented, a useful digital product can start by making the information and next step clearer. The strongest marketplace experiences often begin there, before they become large ecosystems.'
  ]},
  {slug:'product-marketing-starts-before-launch',title:'Product Marketing Starts Before Launch',excerpt:'Product marketing helps shape how a product is understood, positioned and adopted before launch.',category:'Product',publishedAt:'2026-08-16',readTime:'5 min read',content:[
    'Product marketing is often treated as the final step before launch: write the announcement, prepare the campaign and start promoting. In reality, some of the most important product marketing decisions happen much earlier.',
    'Before a product is promoted, a team needs to know who it is for, what problem it solves, why the problem matters and what makes the proposed solution worth considering. Those questions are not only marketing questions. They can influence the product itself.',
    'Positioning is especially useful because it forces clarity. A product cannot be for everyone in a meaningful sense. Choosing a primary audience does not mean excluding every other user, but it does mean deciding whose problem the product is solving first and what promise the product should make to them.',
    'Messaging also reveals gaps. When a team cannot explain a product in a simple way, that can indicate a product problem rather than a copywriting problem. Perhaps the value is unclear. Perhaps the audience has not been defined well enough. Perhaps there are too many features competing for attention.',
    'This is why product marketing should be connected to research, strategy, design and development. Research provides the language and evidence. Strategy turns that into a clear direction. Product design makes the value visible in the experience. Development makes the promise real. Marketing then helps the right people understand and adopt it.',
    'For early-stage products, this can also make marketing more practical. Instead of trying to create broad awareness immediately, a team can focus on the small group most likely to recognise the problem, test the message with them and use what they learn to improve both the product and its positioning.',
    'A product should be useful, understandable and discoverable. Treating marketing as part of product work helps those three qualities reinforce one another.'
  ]}
];

export function getInsight(slug:string){return insights.find(i=>i.slug===slug)}