export type InsightCategory = 'Product Strategy' | 'Research' | 'Product Marketing' | 'Education Technology' | 'Teaching Technology' | 'Technology';
export type Insight = { slug:string; title:string; excerpt:string; category:InsightCategory; publishedAt:string; readTime:string; content:string[] };
export const insights: Insight[] = [
{slug:'what-abe-techlab-builds',title:'What ABE TechLab Actually Builds',excerpt:'A look at the product, research, education technology and technology work behind ABE TechLab.',category:'Product Strategy',publishedAt:'2026-08-16',readTime:'4 min read',content:['ABE TechLab helps turn meaningful problems and ideas into useful digital products. That can mean researching a problem, shaping product strategy, designing the experience, building the technology or helping a product find its market.','Our work spans product research, product strategy, product marketing, design and development. We also work in education and teaching technology, where learners, teachers and institutions all matter.','Projects such as TechTrack, BuMarS and PROQUREMENT reflect different sides of that approach. They share a focus on understanding the problem first and building around the people who use the solution.']},
{slug:'why-product-research-comes-before-building',title:'Why Product Research Should Come Before Building',excerpt:'Good product development starts by understanding the problem, people and opportunity before deciding what to build.',category:'Research',publishedAt:'2026-08-16',readTime:'5 min read',content:['One of the easiest mistakes in product development is starting with a feature list before understanding the problem. A polished interface cannot rescue a product that solves the wrong problem.','Research helps a team test assumptions: who experiences the problem, how they solve it today, what is frustrating and what would make a new solution worth adopting.','Interviews, observation, market analysis, competitor reviews and small experiments can reveal enough to make better decisions.']},
{slug:'teaching-technology-is-more-than-an-lms',title:'Teaching Technology Is More Than an LMS',excerpt:'Technology for education should support the people doing the teaching, not only the platform where lessons are stored.',category:'Teaching Technology',publishedAt:'2026-08-16',readTime:'5 min read',content:['An LMS, or Learning Management System, can organise courses, lessons, assessments and records. Teaching technology has a wider job: making teaching and learning more effective.','Teachers need simple ways to monitor progress, adapt pace, identify struggles and communicate. Students need technology that makes progress, feedback and practice understandable and motivating.','TechTrack is part of ABE TechLab’s exploration of this space. Education products should be designed around the full learning system: students, teachers, institutions and the people supporting them.']},
{slug:'from-construction-problem-to-procurement-platform',title:'From a Construction Problem to a Procurement Platform',excerpt:'How product thinking can turn a fragmented construction procurement experience into a clearer digital marketplace.',category:'Technology',publishedAt:'2026-08-16',readTime:'5 min read',content:['Construction procurement involves materials, suppliers, pricing, availability, specifications and delivery. When those pieces are fragmented, finding the right option becomes unnecessarily difficult.','BuMarS is a construction ecosystem, and PROQUREMENT is the builders marketplace being developed within it. The product direction starts with discovery: helping people find building materials and relevant suppliers more efficiently.','A marketplace is not only a catalogue. Trust, useful information, clear categorisation and a straightforward path from discovery to action all matter.']},
{slug:'product-marketing-starts-before-launch',title:'Product Marketing Starts Before Launch',excerpt:'Product marketing helps shape how a product is understood, positioned and adopted before launch.',category:'Product Marketing',publishedAt:'2026-08-16',readTime:'4 min read',content:['Product marketing is often treated as the final step before launch. Some of the most important product marketing decisions happen much earlier.','Who is the product for? What problem does it solve? Why choose it over an existing alternative? What language makes the value clear? These questions can influence the product itself.','That is why ABE TechLab treats product marketing as part of product work rather than a separate promotional layer. A good product needs to be useful, understandable and discoverable.']}
];
export function getInsight(slug:string){return insights.find(i=>i.slug===slug)}
